config/routes.rb
Rails.application.routes.draw do

  namespace :gibbon_example do
    resources :newsletter_subscriptions, only: [:new, :create]
  end

  namespace :mailchimp_api_example do
    resources :newsletter_subscriptions, only: [:new, :create]
  end
end

app/models/gibbon_example/newsletter.rb
module GibbonExample
  class Newsletter
    def self.subscribe(list_id: list_id, email: email)
      new(list_id)
    end

    def initialize(list_id, api_client: Gibbon::API)
      @list_id = list_id
      @api_client = api_client.new
    end

    def subscribe(email)
      api_client.lists.subscribe({ id: list_id, email: { email: email }, :double_optin => false })
    end

    def api_client
      @api_client
    end

    def list_id
      @list_id
    end
  end
end

app/models/mailchimp_api_example/newsletter.rb
module MailchimpApiExample
  class Newsletter
    def self.subscribe(list_id: list_id, email: email)
      new(list_id)
    end

    def initialize(list_id, api_client: Mailchimp::API, api_key: ENV['MAILCHIMP_API_KEY'])
      @list_id = list_id
      @api_client = api_client.new(api_key)
    end

    def subscribe(email)
      api_client.lists.subscribe(list_id, {'email' => email }, :double_optin => false)
    end

    def api_client
      @api_client
    end

    def list_id
      @list_id
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/gibbon_example/newsletter_subscriptions_controller.rb
module GibbonExample
  class NewsletterSubscriptionsController < ApplicationController
    def new
    end

    def create
      newsletter = Newsletter.new('e42daa6e55')

      if newsletter.subscribe(params[:email])
        flash[:notice] = "Thanks for subscribing to our newsletter!"
        redirect_to new_gibbon_example_newsletter_subscription_path
      else
        flash[:alert] = "We could not add you to our newsletter."
      end
    end
  end
end

app/controllers/mailchimp_api_example/newsletter_subscriptions_controller.rb
module MailchimpApiExample
  class NewsletterSubscriptionsController < ApplicationController
    def new
    end

    def create
      newsletter = Newsletter.new('e42daa6e55')

      if newsletter.subscribe(params[:email])
        flash[:notice] = "Thanks for subscribing to our newsletter!"
        redirect_to new_mailchimp_api_example_newsletter_subscription_path
      else
        flash[:alert] = "We could not add you to our newsletter."
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/gibbon_example/newsletter_subscriptions/new.html.slim
div
  - flash.each do |key, value|
    div class="alert alert-#{key}"
      = value

div
  = form_tag gibbon_example_newsletter_subscriptions_path do

    = field_set_tag 'Newsletter Sign up' do
      = label_tag 'Email'
      = email_field_tag 'email'

    = submit_tag

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MailchimpDemo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/mailchimp_api_example/newsletter_subscriptions/new.html.slim
div
  - flash.each do |key, value|
    div class="alert alert-#{key}"
      = value

div
  = form_tag mailchimp_api_example_newsletter_subscriptions_path do

    = field_set_tag 'Newsletter Sign up' do
      = label_tag 'Email'
      = email_field_tag 'email'

    = submit_tag